teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - SeanBohan
      - daniela-barbosa
      - davidwboswell
      - hartm
      - minyu66
      - thelinuxfoundation
  - name: besu-admin
    maintainers:
      - fab-10
      - garyschulte
      - macfarla
      - matkt
    members:
      - jflo
      - jframe
      - siladu
  - name: besu-contributors
    maintainers:
      - garyschulte
      - jframe
      - macfarla
    members:
      - ConsensysOps
      - non-fungible-nelson
      - cdivitotawela
      - kkaur01
  - name: besu-docs-maintainers
    maintainers:
      - bgravenorst
      - joshuafernandes
    members:
      - alexandratran
      - joaniefromtheblock
      - m4sterbunny
  - name: besu-maintainers
    maintainers:
      - fab-10
      - garyschulte
      - jframe
      - macfarla
    members:
      - Gabriel-Trintinalia
      - ahamlat
      - ajsutton
      - antonydenyer
      - atoulme
      - daniellehrner
      - diega
      - gezero
      - gfukushima
      - jflo
      - joshuafernandes
      - lucassaldanha
      - matkt
      - matthew1001
      - mbaxter
      - pinges
      - siladu
      - usmansaleem
  - name: besu-triage
    maintainers:
      - macfarla
      - non-fungible-nelson
    members:
      - NickSneo
      - cdivitotawela
      - cloudspores
      - ensi321
      - gtebrean
      - kkaur01
      - lu-pinto
      - m4sterbunny
      - Matilda-Clerke
      - matthew1001
repositories:
  - name: governance
    teams:
      lf-staff: maintain
    visibility: public
